### ISSUE TITLE
Kubernetes Ingestor : Add support for GKE cluster using 'google' or 'googleServiceaccount' as authProvider

### ISSUE THREAD

**Issue by zoby35** [TeraSky-OSS/backstage-plugins#25]
**Is your feature request related to a problem? Please describe.**
Using the kubernetes-ingestor plugin with a gke cluster defined as below does not work as the plugin is looking for the "ServiceAccountToken" parameter : 

```
kubernetes:
      serviceLocatorMethod:
        type: 'singleTenant'
      clusterLocatorMethods:
        - type: 'gke'
          projectId: 'xxxxx'
          region: 'europe-west1'
          authProvider: 'google' # or with googleServiceaccount
          skipTLSVerify: false
          skipMetricsLookup: false
          exposeDashboard: true
```
Here the logs : 

```
{"level":"warn","message":"Cluster xxxx does not have a valid service account token.","plugin":"catalog","service":"backstage","span_id":"c9706fcccf1ede39","trace_flags":"01","trace_id":"36175f2a87a3ed580b0707754b0a898f"}
```

**Describe the solution you'd like**
Be able to use the service account specified with "GOOGLE_APPLICATION_CREDENTIALS" environment variable or the service account set at the pod level if Backstage is running on a GKE cluster using the Workload Identity Federation enabled on GKE cluster as the kubernetes plugin is currenly working.

https://cloud.google.com/docs/authentication/application-default-credentials

**Describe alternatives you've considered**
The only way I found is to use the 'config' way with 'ServiceAccount' as authProvider.

**Comment by vrabbi** [comment]
This is currently not supported and can be added to the backlog but is not being actively worked on at this point. Contributions are always welcome to add this support.

**Comment by zoby35** [comment]
OK thanks for your feedback.
I would have love to do it unfortunately I do not have the needed knowledge

**Comment by vrabbi** [comment]
a new release has been cut today with experimental support for other auth methods for the ingestor plugin. it is not something we test currently but hopefully should work with all server side auth methods now of the k8s plugin and defaults back to the service account token method when needed. please let us know if it works for you.
The frontend plugin are still not updated and some may work and other wont yet, but that is in the backlog as well.

**Comment by vrabbi** [comment]
@zoby35 have you gotten a chance to test the latest release?

**Comment by zoby35** [comment]
Yes I did, but upgrading backstage to the latest release 1.37.0 and the kubernetes ingestor plugin to 1.11.0, the "crossplaine-claim" type from the catalog disparears and I'm seeing the below error within the logs. 
Everything is working fine with backstage 1.36.0 and kubernetes ingestor 1.10.2.

`Received 401 status when fetching "/apis/apiextensions.k8s.io/v1/customresourcedefinitions" from cluster "xxxxx"; body=[{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401`

So far I just used the service account auth provider, I just wanted to make sure everything was working fine with the service account before doing some tests with the other authentication method.

I'm still looking what's wrong, I'll let you know once i've made all of my tests.

**Comment by vrabbi** [comment]
fixes were made again in this regard in the latest release

**Comment by zoby35** [comment]
I just tested the latest release "1.12.0", it works perfectly fine with a service account token but when i'm using the google auth method for a GKE cluster i'm having that error : 

`Failed to get auth credentials for cluster xxxxx with provider google: Google auth metadata not found in cluster configuration`

Here is the config I have for the kubernetes plugin : 

```
kubernetes:
      serviceLocatorMethod:
        type: 'singleTenant'
      clusterLocatorMethods:
        - type: 'gke'
          projectId: 'xxxxx'
          region: 'europe-west1'
          authProvider: 'google'
          skipTLSVerify: false
          skipMetricsLookup: false
          exposeDashboard: true
```

Am i missing something?
