### ISSUE TITLE
Unable to ingest resources when cluster name exceeds 63 characters

### ISSUE THREAD

**Issue by sachinmalanki** [TeraSky-OSS/backstage-plugins#32]
**Describe the bug**
I managed to notice this bug when my cluster name was more than 63 characters. 

**To Reproduce**
In app-config.yaml
```
    kubernetes:
      frontend:
        podDelete:
          enabled: true
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - url: https://xxx.gr7.eu-west-1.eks.amazonaws.com #tooling-cluster
              name: tooling_cluster_dev_eks
              title: 'Tooling Cluster'
              authProvider: serviceAccount
              skipTLSVerify: true
              skipMetricsLookup: true
              serviceAccountToken: ${TOOLING_SA}
```
The reason is the deployment name is appended before the cluster name to make it unique for every cluster.
Eg: Deployment `crossplane-contrib-function-go-templating-3fc997d6b713` and cluster name `tooling_cluster_dev_eks` would be `crossplane-contrib-function-go-templating-3fc997d6b713-tooling_cluster_dev_eks`

**Expected behavior**
I should be able to see ingested crossplane claims but nothing shows up as there are no logs mentioning about this error.

![Image](https://github.com/user-attachments/assets/b310a70a-d796-4519-b855-bff8dd6cdb95)

**Desktop (please complete the following information):**
 - OS: linux-amd
 - Browser [e.g. chrome, safari] - chrome
 - Version [e.g. 22] - 135.0.7049.41

**Additional context**
I was able to identify this issue after installing backstage plugin `@backstage/plugin-catalog-backend-module-logs` and adding `backend.add(import('@backstage/plugin-catalog-backend-module-logs'));
` in `backstage-app/app/packages/backend/src/index.ts`
