### ISSUE TITLE
Incorrect Tags Kind displayed in Backstage UI

### ISSUE THREAD

**Issue by haarchri** [TeraSky-OSS/backstage-plugins#43]
**Describe the bug**
After ingestion, the Backstage UI incorrectly displays the kind as `xek` instead of the expected and correct value `XEKS` from the `Kind`. This is misleading and causes confusion for users trying to work with it.

ref:https://github.com/upbound/configuration-aws-eks/blob/main/apis/definition.yaml#L10

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeks.aws.platform.upbound.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: aws.platform.upbound.io
  names:
    kind: XEKS
    plural: xeks
```

<img width="560" alt="Image" src="https://github.com/user-attachments/assets/967017af-5989-4cd9-8ba9-a967b0a4a5cf" />
