### ISSUE TITLE
manifestLayout is missing 

### ISSUE THREAD

**Issue by haarchri** [TeraSky-OSS/backstage-plugins#49]
**Describe the bug**
i try to create a claim via the component - but i only see the Push Manifest to GitOps Repository checkbox - but manifestLayout and TargetClusters is missing  - any idea why this can happen ? 

<img width="1712" alt="Image" src="https://github.com/user-attachments/assets/22cda63a-68ba-4e88-9253-6d9c8cfb023b" />

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JHandy1** [comment]
Just to update on the issue I've seen, it's actually on the XRD status.controllers.compositeResourceType on the cluster that I don't have the mapping for some reason:
```
status:
  conditions:
    - lastTransitionTime: 2025-06-03T08:28:12Z
      reason: WatchingCompositeResourceClaim
      status: "True"
      type: Offered
    - lastTransitionTime: 2025-06-03T08:28:13Z
      reason: WatchingCompositeResource
      status: "True"
      type: Established
  controllers:
    compositeResourceClaimType:
      apiVersion: ""
      kind: ""
    compositeResourceType:
      apiVersion: ""
      kind: ""
```
Not got to the bottom of why yet, but templates from XRDs with this status set correctly work as expected. 

Another thing to note - seems that once one template with an error is started and fails to display the sections correctly, the Backstage UI gets upset and fails to render them on any other template until you refresh the page.

**Comment by vrabbi** [comment]
regarding the issue with needing to refresh the page is an unfortunate issue, but is something related to backstage itself, and the browser cache it seems and there is nothing really i can do in the plugin around this. 
The XRDs when they dont have those status fields wont work indeed and that makes sense because we need those fields, but what we can do in the plugin is not generate templates for XRDs that dont have these fields populated

**Comment by haarchri** [comment]
i can add something more when adding the following config:

```
      kubernetesIngestor:
        mappings:
          systemModel: "cluster-namespace"
        components:
          customWorkloadTypes:
            - group: "aws.platform.upbound.io"
              apiVersion: "v1alpha1"
              plural: "xeks"
              singular: "xeks"
```

all generated components are working - when they belong to the group `aws.platform.upbound.io` - if i have a component in a different group for example `platform.upbound.io` we have the same issue as described

after adding a new resource with the group `platform.upbound.io` the component starts to work too

```
      kubernetesIngestor:
        mappings:
          systemModel: "cluster-namespace"
        components:
          customWorkloadTypes:
            - group: "aws.platform.upbound.io"
              apiVersion: "v1alpha1"
              plural: "xeks"
              singular: "xeks"
            - group: "platform.upbound.io"
              apiVersion: "v1alpha1"
              plural: "xsqlinstances"
```
