### ISSUE TITLE
Kubernetes Ingestor: XRDs scheduler is running even if the XRDs is disabled in the config

### ISSUE THREAD

**Issue by prateekch33** [TeraSky-OSS/backstage-plugins#53]
**Describe the bug**
We are configuring this plugin in our backstage instance to pul only the default workloads, not the crossplane crds/xrds. But even If the xrds enabled is set as false, its still running the scheduler.

**To Reproduce**
1. Set xrds: enabled: false, like

```yaml
kubernetesIngestor:
    crossplane:
         xrds:
             enabled: false
```
2. Check the logs of the system, its trying to pull the xrds from the cluster

**Expected behavior**
It should not try to fetch the XRDs from the cluster as we disabled that

**Reference: My Kubernetes Ingestor Config**

```yaml
kubernetesIngestor:
  components:
    enabled: true
    taskRunner:
      frequency: 1200
      timeout: 600
    excludedNamespaces: []
    disableDefaultWorkloadTypes: false
    onlyIngestAnnotedResources: false
  crossplane:
    claims:
      ingestAllClaims: false
    xrds:
      enabled: false
      taskRunner:
        frequency: 10
        timeout: 600
      ingestAllXRDs: false
      convertDefaultValuesToPlaceholders: true
```
