### ISSUE TITLE
crossplane cannot be disabled

### ISSUE THREAD

**Issue by imbabamba** [TeraSky-OSS/backstage-plugins#58]
I have configured:

kubernetesIngestor:
  mappings:
    namespaceModel: 'default' # cluster, namespace, default
    nameModel: 'name' # name-cluster, name-namespace, name
    titleModel: 'name' # name, name-cluster, name-namespace
    systemModel: 'namespace' # cluster, namespace, cluster-namespace, default
    referencesNamespaceModel: 'default' # default, same
  components:
    # Whether to enable creation of backstage components for Kubernetes workloads
    enabled: true
    taskRunner:
      # How often to query the clusters for data
      frequency: 10
      # Max time to process the data per cycle
      timeout: 600 
    # Namespaces to exclude the resources from
    excludedNamespaces: 
      - kube-public
      - kube-system
      - argocd
    # Custom Resource Types to also generate components for
    # By default all standard kubernetes workload types are ingested. This allows you to disable this behavior
    disableDefaultWorkloadTypes: false
    # Allows ingestion to be opt-in or opt-out by either requiring or not a dedicated annotation to ingest a resource (terasky.backstage.io/add-to-catalog or terasky.backstage.io/exclude-from-catalog)
    onlyIngestAnnotatedResources: true
  crossplane:
    # This section is relevant for crossplane v1 claims as well as Crossplane v2 XRs.
    # In the future when v1 and claims are deprecated this field will change names but currently 
    # for backwards compatibility will stay as is
    claims:
      # Whether to create components for all claim resources (v1) and XRs (v2) in your cluster
      ingestAllClaims: false
    xrds:
      enabled: false

the crossplane: section should disable crossplane, but im getting this looped error even though we don't use crossplane. any ideas? 

`warn Received 403 status when fetching "/apis/apiextensions.crossplane.io/v1/compositions" from cluster "devtrack"; body=[{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"compositions.apiextensions.crossplane.io is forbidden: User \"system:serviceaccount:backstage:backstage\" cannot list resource \"compositions\" in API group \"apiextensions.crossplane.io\" at the cluster scope","reason":"Forbidden","details":{"group":"apiextensions.crossplane.io","kind":"compositions"},"code":403}`

**Comment by vrabbi** [comment]
this has been released in https://github.com/TeraSky-OSS/backstage-plugins/releases/tag/29-06-2025

**Comment by imbabamba** [comment]
@vrabbi it seems I have to configure `crossplane` like this to disable it.

```
      crossplane:
        enabled: false
        # This section is relevant for crossplane v1 claims as well as Crossplane v2 XRs.
        # In the future when v1 and claims are deprecated this field will change names but currently 
        # for backwards compatibility will stay as is
        claims:
          # Whether to create components for all claim resources (v1) and XRs (v2) in your cluster
          ingestAllClaims: false
        xrds:
          enabled: false
```

Still seeing the. "catalog info action=LoadingCustomResources numOfCustomResources=0" what is this?
